### ISSUE TITLE
hard-wired English strings

### ISSUE THREAD

**Issue by germanvaleroelizondo** [MorrisR2/moodle_local_searchquestions#1]
Hi,
I just installed the 'Search Questions' plugin for my Moodle 2.7.4 local server and it looks nice and works as expected.
But there are two hard-coded English language strings, and I think it would be better if they were declared as variables, so that they would be available for translation at AMOS (https://lang.moodle.org).
 The strings are:

Text search
Search answers

I think they would be easy to change and it would improve the plugin for all Moodle sites in languages other than English.
Thanks in advance for your help.

**Comment by sensei-hacker** [comment]
I have pushed a resolution:
https://github.com/MorrisR2/moodle_local_searchquestions/commit/1873a22c0a64e4f78e2dc812aae860d30efe768e
